#!/bin/bash

echo -e "List of edgelists:\n"
echo Erdos
echo grid
echo -e "karate\n"

echo Type the edge list you wish to run:
read edgelist
make EDGELIST=$edgelist
clear
if [ "$edgelist" == "Erdos" ];
then
  echo "Will take some time, sit back and relax :)"
fi
make exec EDGELIST=$edgelist
make clean
